Repository billyjojojobulido/billyjojojobulido.github.io, pull requests merged in 2024-11, with the labels that each got.

#81 new branch -- issue #74
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#82 Notes hash map
  notes/Algorithm/hash_map/chinese/index.html
Labels: bug, enhancement

#83 Notes hash map
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#85 <feat> added picture and more explaination in separate chaining approach
  notes/Algorithm/hash_map/chain.png
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#86 <feat> start working on open addressing
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#87 <feat> explained the open addressing
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#88 <fix> rephrase some redundant expression
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#89 <feat> added img to explain hash map
  notes/Algorithm/hash_map/chinese/index.html
  notes/Algorithm/hash_map/map.png
Labels: enhancement

#90 <feat> more img
  notes/Algorithm/hash_map/chinese/index.html
  notes/Algorithm/hash_map/hash_func.png
  notes/Algorithm/hash_map/open_address.png
Labels: enhancement

#91 <feat> more img
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#93 - start changing url
  notes/Algorithm/hash_map/english/index.html
Labels: enhancement

#94 <fix> change word count
  notes/Algorithm/hash_map/chinese/index.html
Labels: enhancement

#95 - translated overview session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#96 - translated principal session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#97 - translated hash function session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#98 - translated hash collision session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#99 - translated seperate chaining constraint session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#100 - translated open addressing session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#101 - translated B&R tree session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#102 - translated evaluation session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation

#103 - translated reference session
  notes/Algorithm/hash_map/english/index.html
Labels: documentation, enhancement

#104 <feat> add entry for chinese note of hash map
  categories/index.html
  notes/index.html
Labels: documentation, enhancement

#105 <feat> added entry for english notes of hash map
  categories/index.html
  notes/index.html
Labels: enhancement

#106 <fix> changed the note count in notes page
  notes/index.html
Labels: documentation, enhancement

#107 <fix> changed the note count in notes page
  categories/index.html
Labels: enhancement

#110 <fix> fixed some typos
  notes/Algorithm/hash_map/chinese/index.html
Labels: bug, documentation

#112 <feat> added the question list in hashmap chinese notes
  notes/Algorithm/hash_map/chinese/index.html
Labels: documentation, enhancement

#113 <fix> reformat the question list
  notes/Algorithm/hash_map/chinese/index.html
Labels: bug, documentation

#114 <feat> added the question list to hash map english notes
  notes/Algorithm/hash_map/english/index.html
Labels: documentation, enhancement

#115 <fix> some typos fixed
  notes/Algorithm/hash_map/english/index.html
Labels: bug, documentation

#128 <fix> fixed issue #124
  notes/Algorithm/hash_map/chinese/index.html
Labels: bug, documentation

#129 <fix> fixed issue #125
  notes/Algorithm/hash_map/english/index.html
Labels: bug, documentation

#130 <fix> fixed issue #126
  notes/Algorithm/hash_map/chinese/index.html
Labels: bug, documentation

#131 <fix> fixed issue #127
  notes/Algorithm/hash_map/english/index.html
Labels: bug, documentation

#132 [newbranch] start working linked list notes
  notes/Algorithm/linked_list/chinese/index.html
Labels: documentation, enhancement

#133 - added the entry to the chinese notes of linked list
  categories/index.html
  notes/index.html
Labels: documentation, enhancement

#135 - fixed issue #134
  notes/index.html
Labels: bug

#137 - added more information
  notes/Algorithm/linked_list/chinese/index.html
Labels: bug, documentation

#138 N linked list
  notes/Algorithm/linked_list/chinese/index.html
  notes/Algorithm/linked_list/circle_linked_list.jpg
  notes/Algorithm/linked_list/delete.jpg
  notes/Algorithm/linked_list/double_linked_list.jpg
  notes/Algorithm/linked_list/insert.jpg
  notes/Algorithm/linked_list/linked_list.jpg
  notes/Algorithm/linked_list/memory.jpg
  notes/Algorithm/linked_list/node.jpg
Labels: bug, documentation

#140 - start working on english notes of linked list
  notes/Algorithm/linked_list/english/index.html
Labels: documentation, enhancement

#141 F linked list en
  notes/Algorithm/linked_list/english/index.html
Labels: bug, documentation

#143 - fixed the entry order issue
  categories/index.html
Labels: bug

#146 Update README.md
  README.md
Labels: documentation, enhancement

#148 Fix issue 147
  notes/Algorithm/linked_list/chinese/index.html
Labels: bug, documentation

#149 - fix redo the array I notes structure - wip
  notes/Algorithm/array/chinese/index.html
  notes/Algorithm/array/english/highdim.png
  notes/Algorithm/array/english/index.html
  notes/Algorithm/array/img/array-cn.png
  notes/Algorithm/array/img/array-en.png
  notes/Algorithm/array/img/delete-cn.png
  notes/Algorithm/array/img/delete-en.png
  notes/Algorithm/array/img/highdim.png
Labels: enhancement

#150 - fixed the backtracking notes structure issue #84
  notes/Algorithm/backtracking/chinese/index.html
  notes/Algorithm/backtracking/english/index.html
  notes/Algorithm/backtracking/img/combination_tree.png
Labels: enhancement

#152 - fixed the hashmap notes structure issue #84
  notes/Algorithm/hash_map/chinese/index.html
  notes/Algorithm/hash_map/english/index.html
  notes/Algorithm/hash_map/img/chain.png
  notes/Algorithm/hash_map/img/hash_func.png
  notes/Algorithm/hash_map/img/map.png
  notes/Algorithm/hash_map/img/open_address.png
Labels: enhancement

#153 Fix notes structure
  notes/Algorithm/linked_list/chinese/index.html
  notes/Algorithm/linked_list/english/index.html
  notes/Algorithm/linked_list/img/circle_linked_list.jpg
  notes/Algorithm/linked_list/img/delete.jpg
  notes/Algorithm/linked_list/img/double_linked_list.jpg
  notes/Algorithm/linked_list/img/insert.jpg
  notes/Algorithm/linked_list/img/linked_list.jpg
  notes/Algorithm/linked_list/img/memory.jpg
  notes/Algorithm/linked_list/img/node.jpg
Labels: enhancement

#154 Fix notes structure
  notes/Algorithm/prefix_sum/chinese/index.html
  notes/Algorithm/prefix_sum/english/index.html
  notes/Algorithm/prefix_sum/img/2d_presum.png
  notes/Algorithm/prefix_sum/img/presum_demo.png
Labels: enhancement

#156 Fix notes structure
  notes/Algorithm/sort/chinese/index.html
  notes/Algorithm/sort/english/index.html
  notes/Algorithm/sort/english/insert-sort.png
  notes/Algorithm/sort/english/radix-sort1.png
  notes/Algorithm/sort/english/radix-sort2.png
  notes/Algorithm/sort/english/shell-sort.png
  notes/Algorithm/sort/english/tournament1.png
  notes/Algorithm/sort/english/tournament2.png
  notes/Algorithm/sort/img/insert-sort.png
  notes/Algorithm/sort/img/radix-sort1.png
  notes/Algorithm/sort/img/radix-sort2.png
  notes/Algorithm/sort/img/shell-sort.png
  notes/Algorithm/sort/img/tournament1.png
  notes/Algorithm/sort/img/tournament2.png
Labels: enhancement

#157 Fix notes structure
  notes/Algorithm/unionfind/chinese/index.html
  notes/Algorithm/unionfind/english/index.html
  notes/Algorithm/unionfind/img/union-find-1.jpg
  notes/Algorithm/unionfind/img/union-find-2.jpg
  notes/Algorithm/unionfind/img/union-find-3.jpg
  notes/Algorithm/unionfind/img/union-find-4.jpg
Labels: enhancement

#158 Fix issue 155
  notes/Algorithm/sort/chinese/index.html
  notes/Algorithm/sort/english/index.html
  notes/Algorithm/sort/img/shell-sort-ch.png
  notes/Algorithm/sort/img/shell-sort-en.png
Labels: bug, documentation

#159 Fix issue 151
  notes/Algorithm/backtracking/english/index.html
  notes/Algorithm/backtracking/img/combination_tree_ch.png
  notes/Algorithm/backtracking/img/combination_tree_en.png
Labels: bug, documentation, enhancement

#161 Fix issue 116
  notes/Algorithm/array/chinese/index.html
  notes/Algorithm/array/english/index.html
  notes/Algorithm/backtracking/chinese/index.html
Labels: documentation, enhancement

#162 Fix issue 117
  notes/Algorithm/sort/chinese/index.html
  notes/Algorithm/sort/english/index.html
Labels: enhancement

#163 Fix issue 118
  notes/Algorithm/bisection/chinese/index.html
  notes/Algorithm/bisection/english/index.html
Labels: enhancement

#164 Fix issue 119
  notes/Algorithm/divide_and_conquer/chinese/index.html
Labels: enhancement

#166 Fix issue 121
  notes/Algorithm/hash_map/chinese/index.html
  notes/Algorithm/hash_map/english/index.html
Labels: enhancement

#168 - fixed issue #122 (2/2)
  notes/Algorithm/twopointer/english/index.html
Labels: enhancement

#169 Fix issue 123
  notes/Algorithm/unionfind/chinese/index.html
  notes/Algorithm/unionfind/english/index.html
Labels: enhancement

#170 Fix issue 167
  notes/Algorithm/linked_list/chinese/index.html
  notes/Algorithm/linked_list/english/index.html
Labels: enhancement

#173 Fix issue 171
  notes/Algorithm/backtracking/chinese/index.html
  notes/Algorithm/backtracking/english/index.html
Labels: enhancement

#174 Fix issue 172
  notes/Algorithm/greedy/chinese/index.html
  notes/Algorithm/greedy/english/index.html
Labels: enhancement

#176 Improve expression in Sort notes (en)
  notes/Algorithm/sort/english/index.html
Labels: documentation, enhancement

#177 improve expression in d&c notes (ch)
  notes/Algorithm/divide_and_conquer/chinese/index.html
Labels: documentation, enhancement

#179 unify the case of time complexity
  notes/Algorithm/prefix_sum/chinese/index.html
Labels: documentation, enhancement

#180 unify the case of time complexity in prefix sum notes(en)
  notes/Algorithm/prefix_sum/english/index.html
Labels: documentation, enhancement

#183 F issue 144
  notes/Algorithm/string/chinese/index.html
Labels: enhancement

#184 F issue 144
  notes/Algorithm/string/chinese/index.html
Labels: enhancement

#185 F issue 144
  notes/Algorithm/string/chinese/index.html
Labels: enhancement

#186 Fix Typo in prefix sum notes (ch)
  notes/Algorithm/prefix_sum/chinese/index.html
Labels: documentation, enhancement

#187 change the expression of "array array" in prefix sum notes (en)
  notes/Algorithm/prefix_sum/english/index.html
Labels: enhancement

#188 - more explanation on Leetcode 151
  notes/Algorithm/string/chinese/index.html
Labels: documentation, enhancement

#189 F issue 144
  notes/Algorithm/string/chinese/index.html
Labels: documentation, enhancement

#190 F issue 144
  notes/Algorithm/string/chinese/index.html
Labels: enhancement

#191 Update entry for string notes (ch) on notes page
  notes/index.html
Labels: enhancement

#192 added entry for string notes (ch) on category page
  categories/index.html
Labels: enhancement

#193 Update README.md ++ TODO Vault
  README.md
Labels: documentation

#194 Update category for new source of array notes
  categories/index.html
Labels: enhancement

#208 - issue #207 FIXED :: dropped the array folder after source shift
  notes/Algorithm/array/chinese/index.html
  notes/Algorithm/array/english/index.html
  notes/Algorithm/array/img/array-cn.png
  notes/Algorithm/array/img/array-en.png
  notes/Algorithm/array/img/delete-cn.png
  notes/Algorithm/array/img/delete-en.png
  notes/Algorithm/array/img/highdim.png
Labels: enhancement
